server:
  port: 8585
  error:
    include-stacktrace: never
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_dimex?useSSL=false&serverTimeZone=America_Los_Angeles"
    username: "root"
    password: "77661151"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-plataform: "org.hibernate.dialect.MySQL8Dialect"
    show-sql: true
    hibernate:
      ddl-auto: "create-drop"
login:
  level:
    org:
      hibernate:
        SQL: "debug"
      
jms:
  jwt:
    security:
      enabled: true
    timezone: "America/Los_Angeles"
    issuer: "www.dimex.com"
    token: 
      auth: 
        path: "/v1.0/oauth/client_credential/accesstoken"
      secret: "emmanuel_hernandez@private_key"
      expires-in: 3600 #seconds
    excluded: 
      path: "/v1.0/multi,v1.0/otraexclusion"
      
      
      
  